from selenium.webdriver.common.by import By

class CreateOrderPageLocators():
    HEADER_ORDER_BUTTON = (By.XPATH,".//div[@class='Header_Nav__AGCXC']/button[contains(text(), 'Заказать')]")
    BODY_ORDER_BUTTON = (By.XPATH, ".//div[@class='Home_FinishButton__1_cWm']/button[contains(text(), 'Заказать')]")
    NAME_INPUT = (By.XPATH, ".//input[@placeholder='* Имя']")
    SURNAME_INPUT = (By.XPATH, ".//input[@placeholder='* Фамилия']")
    ADDRESS_INPUT = (By.XPATH, ".//input[@placeholder='* Адрес: куда привезти заказ']")
    PHONE_INPUT = (By.XPATH, ".//input[@placeholder='* Телефон: на него позвонит курьер']")
    METRO_INPUT = (By.XPATH, ".//input[@placeholder='* Станция метро']")
    METRO_CHERKIZOVSKAYA = (By.XPATH, ".//div[@class='Order_Text__2broi' and text()='Черкизовская']")
    METRO_SOKOLNIKI = (By.XPATH, ".//div[@class='Order_Text__2broi' and text()='Сокольники']")
    NEXT_BUTTON = (By.XPATH, ".//button[contains(text(), 'Далее')]")
    DATE_INPUT = (By.XPATH, ".//input[@placeholder='* Когда привезти самокат']")
    DATE_SELECT_13_DAY = (By.XPATH, ".//div[@class='react-datepicker__week']/div[contains(text(), '13')]")
    DATE_SELECT_29_DAY = (By.XPATH, ".//div[@class='react-datepicker__week']/div[contains(text(), '29')]")
    TIME_RENT_INPUT = (By.XPATH, ".//div[@class='Dropdown-control']")
    TIME_RENT_SELECT_2_DAY = (By.XPATH, ".//div[@class='Dropdown-option'][1]")
    TIME_RENT_SELECT_3_DAY = (By.XPATH, ".//div[@class='Dropdown-option'][2]")
    COLOR_SELECT_BLACK = (By.ID, 'black')
    COLOR_SELECT_GREY = (By.ID, 'grey')
    COMMENT = (By.XPATH, ".//input[@placeholder='Комментарий для курьера']")
    FORM_ORDER_BUTTON = (By.XPATH, ".//div[@class='Order_Buttons__1xGrp']/button[contains(text(), 'Заказать')]")
    CONFIRM_ORDER_BUTTON = (By.XPATH, ".//div[@class='Order_Buttons__1xGrp']/button[contains(text(), 'Да')]")
    SUCCESS_ORDER_MODAL = (By.XPATH, ".//div[@class='Order_Modal__YZ-d3']")
    CHECK_ORDER_STATUS = (By.XPATH, ".//button[contains(text(), 'Посмотреть статус')]")
